version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "goomer"
      POSTGRES_USER: "goomer-user"
      POSTGRES_PASSWORD: "goomer-password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
